### ISSUE TITLE
Improve the documentation website rendering such that code blocks are wider on wider screens

### ISSUE THREAD

**Issue by RaghuSpaceRajan** [Farama-Foundation/Gymnasium#1280]
### Proposal

When going through the documentation website and going to the source code from there, the code blocks that appear on the next page have a scrollbar at the bottom if the code is too long to fit inside the code block. While this may be okay on narrower screens, on wider screens still having a narrow code block leads to a poorer experience, because we need to constantly go to the bottom of the page to adjust the scrollbar of the code block. Please see the attached screenshot of [this doc page](https://gymnasium.farama.org/_modules/gymnasium/wrappers/rendering/#RecordVideo) the scrollbar on Google Chrome. My proposal is to set the width of these code blocks adaptively based on the window width of the browser.

![gymnasium_docs_screenshot_20241220_203623](https://github.com/user-attachments/assets/83ba665e-cb86-430b-a1b7-a9036ccc6a6a)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the suggestion @RaghuSpaceRajan 

@mgoulao Do you have any ideas? Looking online (chatgpt) we could specify a custom css file in `conf.py` that contains custom code-block css, 
```css
.highlight pre {
    max-width: 80%; /* Or set a fixed width like 800px */
    margin: auto;   /* Center the code block */
    overflow: auto; /* Add scrollbars if content overflows */
}
```
Do you think this could work?
